import Foundation
import SwiftUI

enum AppResolvedLanguage: String, Equatable {
    case english
    case simplifiedChinese
}

enum AppLanguageMode: String, CaseIterable, Identifiable {
    case system
    case english
    case simplifiedChinese

    var id: String {
        rawValue
    }

    var resolvedLanguage: AppResolvedLanguage {
        switch self {
        case .system:
            return Self.systemResolvedLanguage
        case .english:
            return .english
        case .simplifiedChinese:
            return .simplifiedChinese
        }
    }

    func title(language: AppResolvedLanguage) -> String {
        switch self {
        case .system:
            return L10n.t("System", language)
        case .english:
            return "English"
        case .simplifiedChinese:
            return "简体中文"
        }
    }

    var systemImageName: String {
        switch self {
        case .system:
            return "globe"
        case .english:
            return "character.book.closed"
        case .simplifiedChinese:
            return "character.book.closed.zh"
        }
    }

    private static var systemResolvedLanguage: AppResolvedLanguage {
        let preferred = Locale.preferredLanguages.first?.lowercased() ?? ""
        return preferred.hasPrefix("zh") ? .simplifiedChinese : .english
    }
}

enum AILanguageMode: String, CaseIterable, Identifiable {
    case auto
    case chinese
    case english

    var id: String {
        rawValue
    }

    func title(language: AppResolvedLanguage) -> String {
        switch self {
        case .auto:
            return L10n.t("Auto", language)
        case .chinese:
            return L10n.t("Chinese", language)
        case .english:
            return L10n.t("English", language)
        }
    }

    func subtitle(language: AppResolvedLanguage) -> String {
        switch self {
        case .auto:
            return L10n.t("Follow the audio language", language)
        case .chinese:
            return L10n.t("Always summarize in Chinese", language)
        case .english:
            return L10n.t("Always summarize in English", language)
        }
    }

    var requestValue: String {
        switch self {
        case .auto:
            return "auto"
        case .chinese:
            return "zh"
        case .english:
            return "en"
        }
    }
}

private struct AppLanguageEnvironmentKey: EnvironmentKey {
    static let defaultValue: AppResolvedLanguage = AppLanguageMode.system.resolvedLanguage
}

extension EnvironmentValues {
    var appLanguage: AppResolvedLanguage {
        get { self[AppLanguageEnvironmentKey.self] }
        set { self[AppLanguageEnvironmentKey.self] = newValue }
    }
}

enum L10n {
    static func t(_ key: String, _ language: AppResolvedLanguage) -> String {
        guard language == .simplifiedChinese else {
            return key
        }

        return simplifiedChinese[key] ?? key
    }

    static func tagName(_ tag: TimelineTag, language: AppResolvedLanguage) -> String {
        guard tag.isDefaultPrimaryTag else {
            return tag.name
        }

        return DefaultPrimaryTagLocalization.displayName(for: tag.name, language: language)
    }

    static func defaultPrimaryTagSearchNames(for tag: TimelineTag) -> [String] {
        guard tag.isDefaultPrimaryTag else {
            return [tag.name]
        }

        return DefaultPrimaryTagLocalization.searchNames(for: tag.name)
    }

    private static let simplifiedChinese: [String: String] = [
        "24h distribution": "24 小时分布",
        "Add": "添加",
        "Add alias": "添加别名",
        "Add from Library": "从相册添加",
        "Add Photos": "添加照片",
        "Add Video": "添加视频",
        "Add Primary Tag": "添加主标签",
        "Add Topic Tag": "添加主题标签",
        "Advanced": "高级",
        "Advanced Sync": "高级同步",
        "Advanced Rendering": "高级渲染",
        "Allow dollar-sign formula syntax": "允许美元符号公式语法",
        "Allow HTML-shaped Markdown source": "允许 HTML 形态的 Markdown 源码",
        "Allow Markdown image URLs to render inline": "允许 Markdown 图片 URL 行内渲染",
        "Default Rendering": "默认渲染",
        "Enable": "开启",
        "Keep Off": "保持关闭",
        "Markdown": "Markdown",
        "Markdown Rendering": "Markdown 渲染",
        "Markdown syntax stays optional. The composer remains a plain source editor with compact heading controls only.": "Markdown 语法保持可选。编辑器仍是源码输入，并只保留紧凑的标题控制。",
        "Math Formulas": "数学公式",
        "Math formulas are useful for rare technical notes and can make long Markdown rendering heavier.": "数学公式适合少数技术笔记，可能让较长 Markdown 的渲染更重。",
        "Raw HTML": "Raw HTML",
        "Raw HTML is only for trusted source you wrote yourself. Script-like HTML remains unsafe for private notes.": "Raw HTML 只适合你自己写下的可信来源。类似脚本的 HTML 对私密笔记仍然不安全。",
        "Remote Images": "远程图片",
        "Remote images can reveal when a private moment is viewed by requesting external URLs.": "远程图片会请求外部 URL，可能暴露一条私密记录何时被查看。",
        "System Markdown": "系统 Markdown",
        "Syntax support without extra editor buttons": "支持语法，不增加编辑器按钮",
        "These options are for specialized notes. Leave them off for normal private timeline use.": "这些选项只适合特殊笔记。普通私密时间线使用保持关闭即可。",
        "AI Language": "AI 语言",
        "AI Language affects new summaries and reviews. App language stays separate.": "AI 语言只影响新生成的摘要和回顾，界面语言保持独立。",
        "AI & Tags": "AI 与标签",
        "Area": "分类方向",
        "Areas": "分类方向",
        "AI not ready": "AI 未完成",
        "AI Review": "AI 回顾",
        "AI Analysis is off": "AI 分析已关闭",
        "AI Title Auto-Insert": "AI 标题自动嵌入",
        "AI assignments": "AI 分配",
        "Alias": "别名",
        "Aliases": "别名",
        "Active": "开启",
        "Active days": "活跃天数",
        "Afternoon": "下午",
        "All": "全部",
        "All clear": "全部正常",
        "All icons": "全部图标",
        "Any": "全部",
        "Account": "账号",
        "iCloud accepted the account and container, but the private CloudKit database is currently rejecting even a minimal test write. Your local Ownlight data remains safe and nothing was uploaded. Try again later; if it keeps happening, use the diagnostic logs when contacting Apple Developer Support.": "iCloud 已接受当前账号和容器配置，但私有 CloudKit 数据库现在连最小测试写入都在拒绝。你的本机 Ownlight 数据仍然安全，没有任何内容被上传。可以稍后重试；如果持续出现，请带上诊断日志联系 Apple Developer Support。",
        "iCloud write is currently unavailable. Local data was not uploaded.": "iCloud 写入当前不可用。本地数据没有被上传。",
        "iCloud write unavailable": "iCloud 写入不可用",
        "Appearance": "外观",
        "Archive": "归档",
        "Archive repository": "归档仓库",
        "Archived": "已归档",
        "Attributes": "属性",
        "Audio and video": "音频和视频",
        "Automatic Sync": "自动同步",
        "Automatic Sync is off. New work stays on this iPhone until you tap Sync Now or turn it back on.": "自动同步已关闭。新内容会留在这台 iPhone 上，直到你点击立即同步或重新打开自动同步。",
        "Available": "可用",
        "Auto-generate Weekly Review": "自动生成每周回顾",
        "Overview": "概览",
        "Auto": "自动",
        "Available disk": "可用磁盘",
        "Backup": "备份",
        "Backup actions stay in Mac Admin.": "备份操作仍在 Mac Admin 中执行。",
        "Backup check": "备份检查",
        "Backup info and future private sync": "备份信息与未来私有同步",
        "Backup Status": "备份状态",
        "Blocked": "已阻塞",
        "Calendar": "日历",
        "Cancel": "取消",
        "Camera": "相机",
        "Category": "类别",
        "Chinese": "中文",
        "Choose a preset or enter a valid SF Symbol name.": "选择预设图标，或输入有效的 SF Symbol 名称。",
        "Choose": "选择",
        "Checking archive": "正在检查归档",
        "Check Again": "重新检查",
        "Cancel Export": "取消导出",
        "Clear": "清除",
        "Clear Audio and Video Cache": "清除音频和视频缓存",
        "Clear Filters": "清除筛选",
        "Clear Month Filter": "清除月份筛选",
        "Clear Search": "清除搜索",
        "Close": "关闭",
        "Comment text": "评论内容",
        "Commented": "有评论",
        "Comments": "评论",
        "Completed": "已完成",
        "Connection": "连接",
        "Connection failed": "连接失败",
        "Connection works": "连接正常",
        "Content": "内容",
        "Continue Editing Draft": "继续编辑草稿",
        "Container": "容器",
        "Copied": "已复制",
        "Copy": "复制",
        "Copy text": "复制正文",
        "Configured": "已配置",
        "CloudKit data sync is not enabled in this build. This screen only checks whether iCloud is available for setup.": "当前构建还没有启用 CloudKit 数据同步。这个页面只检查 iCloud 是否可用于后续设置。",
        "CloudKit is not configured for this build yet.": "当前构建还没有配置 CloudKit。",
        "CloudKit is not ready on this device yet. Current status: %@.": "这台设备上的 CloudKit 还没有准备好。当前状态：%@。",
        "CloudKit default zone test uploaded one probe.": "CloudKit 默认 zone 测试已上传一条 probe。",
        "CloudKit smoke test uploaded one test Moment.": "CloudKit smoke test 已上传一条测试记录。",
        "Created": "创建时间",
        "Creates one explicit test Moment and uploads only that record. Existing timeline history is not uploaded by this smoke test.": "创建一条明确的测试记录，并只上传这一条。这个 smoke test 不会上传已有时间线历史。",
        "Custom HEX color": "自定义 HEX 颜色",
        "Custom icon": "自定义图标",
        "Could not determine": "无法判断",
        "Dark": "深色",
        "Database": "数据库",
        "Date": "日期",
        "Daily": "日常",
        "Day Review": "当天回看",
        "Daily rhythm": "每日节奏",
        "Delete": "删除",
        "Delete Permanently": "永久删除",
        "Delete comment?": "删除评论？",
        "Delete Review": "删除回顾",
        "Delete review?": "删除这篇回顾？",
        "Delete summary?": "删除摘要？",
        "Delete this moment?": "删除这条记录？",
        "Deleting review": "正在删除回顾",
        "Device": "设备",
        "Device ID": "设备 ID",
        "Diagnostics": "诊断",
        "Discard": "丢弃",
        "Discard Draft": "丢弃草稿",
        "Discard draft?": "丢弃草稿？",
        "Document file is unavailable.": "文档文件不可用。",
        "Document moment": "文档记录",
        "Document scanner is not available on this device.": "这台设备不可用文档扫描。",
        "Done": "完成",
        "Downloaded Media Cache": "已下载媒体缓存",
        "Edit Moment": "编辑记录",
        "Edit Tags": "编辑标签",
        "English": "英文",
        "Enter a valid SF Symbol name.": "请输入有效的 SF Symbol 名称。",
        "Error": "错误",
        "Evening": "晚上",
        "Export": "导出",
        "Export Data": "导出数据",
        "Export Private Archive?": "导出私密归档？",
        "Failed": "失败",
        "Favorite": "收藏",
        "Favorites": "收藏",
        "Feature Modules": "功能模块",
        "Feedback": "反馈",
        "Filter moments": "筛选记录",
        "Files": "文件",
        "Finished": "完成时间",
        "Food": "饮食",
        "More media": "更多媒介",
        "No check-ins for this item": "这个项目还没有打卡",
        "Photo": "照片",
        "Remove photo": "移除照片",
        "Filter calendar": "筛选日历",
        "Follow the audio language": "跟随音频主体语言",
        "Future date": "未来日期",
        "Generate Last 7 Days": "生成最近 7 天",
        "Generated by": "生成来源",
        "Generating": "正在生成",
        "Generating review": "正在生成回顾",
        "Gentle Suggestions": "温和建议",
        "Hide this theme": "隐藏这个主题",
        "History": "历史",
        "Host": "主机",
        "Image unavailable": "图片不可用",
        "iCloud": "iCloud",
        "iCloud Sync": "iCloud 同步",
        "iCloud Sync is off by default. Ownlight uses your Apple iCloud account and private CloudKit database when you turn it on.": "iCloud 同步默认关闭。开启后，Ownlight 会使用你的 Apple iCloud 账号和私有 CloudKit 数据库。",
        "iCloud Sync is off by default. It uses your iCloud private database and does not require a separate Ownlight account.": "iCloud 同步默认关闭。开启后会使用你的 iCloud 私有数据库，不需要单独的 Ownlight 账号。",
        "iCloud Sync is off.": "iCloud 同步已关闭。",
        "iCloud Sync is on.": "iCloud 同步已开启。",
        "iCloud Sync unavailable": "iCloud 同步不可用",
        "iCloud Sync is off": "iCloud 同步已关闭",
        "iCloud Sync is offline": "iCloud 同步离线",
        "iCloud Sync did not finish": "iCloud 同步未完成",
        "iCloud Sync paused to protect data": "为保护数据，iCloud 同步已暂停",
        "iCloud storage is full": "iCloud 存储空间已满",
        "iCloud is temporarily unavailable": "iCloud 暂时不可用",
        "iCloud Sync is restricted": "iCloud 同步受到限制",
        "Sign in to iCloud": "登录 iCloud",
        "Check your connection. Ownlight will keep working locally and will retry later.": "请检查网络连接。Ownlight 会继续在本机工作，并稍后自动重试。",
        "Free up iCloud storage or change your iCloud plan, then try Sync Now again. Your local data remains on this device.": "请释放 iCloud 存储空间或调整 iCloud 方案，然后再次尝试立即同步。你的本机数据仍保留在这台设备上。",
        "Your local data remains on this device. Try again later; Ownlight will retry automatically when iCloud recovers.": "你的本机数据仍保留在这台设备上。可以稍后再试；iCloud 恢复后 Ownlight 会自动重试。",
        "Ownlight remains available locally. Try again later, or use Sync Now after checking your connection.": "Ownlight 仍可在本机使用。可以稍后重试，或检查网络后再使用立即同步。",
        "Sign in to iCloud in iOS Settings, then return to Ownlight and try Sync Now again.": "请先在 iOS 设置中登录 iCloud，然后回到 Ownlight 再次尝试立即同步。",
        "This build cannot access the configured iCloud container. Your local data remains on this device.": "当前构建无法访问已配置的 iCloud container。你的本机数据仍保留在这台设备上。",
        "iCloud is restricted for this Apple Account or device. Ownlight remains available locally.": "这个 Apple Account 或设备的 iCloud 受到限制。Ownlight 仍可在本机使用。",
        "CloudKit is not configured for this build.": "当前构建没有配置 CloudKit。",
        "iCloud already has an Ownlight library, and this device also has local Ownlight data. To avoid silently merging or overwriting private data, export or clear this device before turning on iCloud Sync.": "iCloud 中已经有一个 Ownlight 资料库，而这台设备也有本机 Ownlight 数据。为避免静默合并或覆盖私人数据，请先导出或清空这台设备，再开启 iCloud 同步。",
        "iCloud is available. Sync remains off until the CloudKit data pipeline is ready.": "iCloud 可用。CloudKit 数据管线完成前，同步仍保持关闭。",
        "iCloud is available. Turn on iCloud Sync when you are ready to use CloudKit.": "iCloud 可用。准备好使用 CloudKit 时，可以开启 iCloud 同步。",
        "iCloud is available. Turn on iCloud Sync when you are ready.": "iCloud 可用。准备好后可以开启 iCloud 同步。",
        "iCloud is not ready on this device yet. Current status: %@.": "这台设备上的 iCloud 还没有准备好。当前状态：%@。",
        "iCloud Sync is not configured for this build yet.": "这个构建尚未配置 iCloud 同步。",
        "iCloud is restricted on this device. Ownlight remains available locally.": "这台设备上的 iCloud 受到限制。Ownlight 仍可在本机使用。",
        "iCloud is temporarily unavailable. Ownlight remains available locally.": "iCloud 暂时不可用。Ownlight 仍可在本机使用。",
        "Import": "导入",
        "Import Archive": "导入归档",
        "Import Archive?": "导入归档？",
        "Import restores a local archive only when this iPhone has no existing local records. It does not merge or overwrite data.": "仅当这台 iPhone 没有现有本机记录时，导入才会恢复本地归档。它不会合并或覆盖数据。",
        "Import is only available when this iPhone has no existing local records. It does not merge or overwrite data.": "仅当这台 iPhone 没有现有本机记录时才可导入。它不会合并或覆盖数据。",
        "Importing archive": "正在导入归档",
        "Importing shared item": "正在导入分享内容",
        "Idle": "空闲",
        "Initialized": "已初始化",
        "Invalid HEX": "HEX 无效",
        "Invalid icon": "无效图标",
        "Jump to Month": "跳到该月",
        "Jump to date": "跳转日期",
        "Key file": "密钥文件",
        "Late Night": "深夜",
        "Latest backup job": "最近备份任务",
        "Latest snapshot": "最近快照",
        "Light": "浅色",
        "Linked": "已连接",
        "Local": "本机",
        "Local mode": "本地模式",
        "Local-only": "仅本地",
        "Local-only mode keeps new work on this iPhone until you tap Sync Now or turn automatic sync back on.": "仅本地模式会把新内容保留在这台 iPhone 上，直到你点击立即同步或重新打开自动同步。",
        "Log In": "登录",
        "Log In First": "先登录",
        "Log Out": "退出登录",
        "Logging In": "正在登录",
        "Login": "登录",
        "Last backup": "最近备份",
        "Last rejected sync": "最近拒绝同步",
        "Last snapshot": "最近快照",
        "Last successful sync": "最近成功同步",
        "Mac Server": "Mac 服务器",
        "Mac Admin can store the Archive repository in a user-selected iCloud Drive folder. The server treats it as a normal folder, not an app-managed cloud upload.": "Mac Admin 可以把 Archive 仓库放在用户选择的 iCloud Drive 文件夹里。Server 只把它当作普通文件夹，不做 app 管理的云上传。",
        "Mac Archive": "Mac Archive",
        "Mac Operations": "Mac 运维",
        "Mac change version": "Mac 变更版本",
        "Mac reachability": "Mac 可达性",
        "Maintenance": "维护模式",
        "Manage": "管理",
        "Manage check-ins": "管理打卡",
        "Manual assignments": "手动分配",
        "Match Source": "命中来源",
        "Media": "媒体",
        "Media cache": "媒体缓存",
        "Media files": "媒体文件",
        "Media unavailable": "媒体不可用",
        "Merge": "合并",
        "Merge Into": "合并到",
        "Merge Selected...": "合并所选...",
        "Merge and Archive This Tag": "合并并归档此标签",
        "Moment": "记录",
        "Moments": "记录",
        "Ownlight cannot verify exact backup completion or Apple-reported per-app backup status.": "Ownlight 不能验证精确的备份完成时间，或 Apple 报告的单个 app 备份状态。",
        "Ownlight will use your iCloud private database. Your current local library will be queued for private iCloud sync in small background batches. Your local data stays on this iPhone.": "Ownlight 会使用你的 iCloud 私有数据库。当前本机资料库会以小批量后台任务进入私有 iCloud 同步队列，你的本机数据仍保留在这台 iPhone 上。",
        "Ownlight could not determine iCloud status. Try again later.": "Ownlight 无法判断 iCloud 状态。请稍后再试。",
        "Month Stats": "月度统计",
        "Morning": "上午",
        "Movement": "运动",
        "Mind": "精神",
        "Name": "名称",
        "Needs attention": "需要处理",
        "Missing media": "缺失媒体",
        "Missed the point": "没有抓住重点",
        "New Moment": "新记录",
        "New Tag": "新标签",
        "New check-in": "新打卡",
        "Next backup": "下次备份",
        "No": "否",
        "No aliases": "没有别名",
        "No backup job yet": "还没有备份任务",
        "No matching icons": "没有匹配的图标",
        "No check-ins yet": "还没有打卡",
        "No records in this time bucket": "这个时间段还没有记录",
        "No snapshot yet": "还没有快照",
        "No time visualization": "未开启时间可视化",
        "No pending operations": "没有待处理操作",
        "No repair action available": "没有可用的修复动作",
        "No sync problems found.": "没有发现同步问题。",
        "No tags": "没有标签",
        "No moments on this day": "这一天没有记录",
        "No moments yet": "还没有记录",
        "Not accepted": "未允许",
        "Not configured": "未配置",
        "Not Now": "暂不",
        "No weekly reviews yet": "还没有每周回顾",
        "No target topic tags": "没有可合并的主题标签",
        "No topic tags yet": "还没有主题标签",
        "None": "无",
        "Not enabled in this build": "当前构建未启用",
        "Not initialized": "未初始化",
        "Not logged in": "未登录",
        "OK": "好",
        "Off": "关闭",
        "Only the available audio slots were added.": "只添加了剩余可用数量的音频。",
        "Only the available photo slots were added.": "只添加了剩余可用数量的照片。",
        "Optional repository path": "可选仓库路径",
        "Open day review": "打开当天回看",
        "Open loops": "开放循环",
        "Open moment preview": "打开记录预览",
        "Open moment detail": "打开记录详情",
        "Open Settings and log in to your private sync endpoint.": "打开设置并登录你的私有同步端点。",
        "Operation counts do not include private text bodies.": "操作计数不包含私人正文内容。",
        "Organization": "组织",
        "Outbox": "发件箱",
        "Password": "密码",
        "Pending changes": "待同步变更",
        "Pending uploads": "待上传",
        "Paths": "路径",
        "Progress": "进展",
        "Queued": "排队中",
        "Progress and Open Loops": "进展与开放循环",
        "Review AI Permission": "查看 AI 许可",
        "Reset AI Permission": "重置 AI 许可",
        "Publish as Moment": "加入时间线",
        "Publish Weekly Review": "发布每周回顾",
        "Recent Records": "最近记录",
        "Pull Server Changes": "拉取服务器变更",
        "Posts": "内容",
        "Primary": "主标签",
        "Private": "私有",
        "Privacy & Support": "隐私与支持",
        "Privacy and support pages open in your browser.": "隐私政策和支持页面会在浏览器中打开。",
        "Privacy Permission": "隐私许可",
        "Privacy Policy": "隐私政策",
        "Private iCloud sync will use your Apple iCloud account and CloudKit private database. This build only checks iCloud availability; it does not upload Ownlight data yet.": "私有 iCloud 同步会使用你的 Apple iCloud 账号和 CloudKit 私有数据库。当前构建只检查 iCloud 可用性，还不会上传 Ownlight 数据。",
        "Private iCloud sync uses your Apple iCloud account and CloudKit private database. It does not require a separate Ownlight account.": "私有 iCloud 同步使用你的 Apple iCloud 账号和 CloudKit 私有数据库，不需要单独的 Ownlight 账号。",
        "Primary Tag": "主标签",
        "Primary Tags": "主标签",
        "Previous month": "上个月",
        "Processing video": "正在处理视频",
        "Promote": "切换准备",
        "Publish": "发布",
        "Publishing": "正在发布",
        "Ready": "已完成",
        "Ready for setup": "可继续设置",
        "Reason": "原因",
        "Rebuild From Server": "从服务器重建",
        "Rebuilding": "正在重建",
        "Reachable": "可连接",
        "Re-download Missing Media": "重新下载缺失媒体",
        "Refresh diagnostics": "刷新诊断",
        "Recent Reviews": "最近回顾",
        "Recent failed job": "最近失败任务",
        "Recovery files": "恢复文件",
        "Regenerate": "重新生成",
        "Regenerating": "正在重新生成",
        "Regenerating review": "正在重新生成回顾",
        "Review deleted": "回顾已删除",
        "Review failed": "回顾生成失败",
        "Reviews": "回顾",
        "Rhythm": "节奏",
        "records": "条记录",
        "Remove audio or video before adding photos.": "请先移除音频或视频，再添加照片。",
        "Remove document": "移除文档",
        "Remove existing media before adding a document.": "请先移除已有媒体，再添加文档。",
        "Remove existing media before adding a video.": "请先移除已有媒体，再添加视频。",
        "Remove favorite": "取消收藏",
        "Remove photos or video before adding audio.": "请先移除照片或视频，再添加音频。",
        "Remove photos, video, or document before adding audio.": "请先移除照片、视频或文档，再添加音频。",
        "Repository": "仓库",
        "Repository path": "仓库路径",
        "Restricted": "受限",
        "Restore": "恢复",
        "Restore Selected": "恢复所选",
        "Restic": "Restic",
        "Retry Uploads": "重试上传",
        "Running": "运行中",
        "Running job": "运行中任务",
        "Save": "保存",
        "Save Changes": "保存更改",
        "Save Server": "保存服务器",
        "Scan": "扫描",
        "Search": "搜索",
        "Search icons": "搜索图标",
        "Search match sources": "搜索命中来源",
        "Send": "发送",
        "Server": "服务器",
        "Server & Device": "服务器与设备",
        "Server failed media": "服务器失败媒体",
        "Server pending ops": "服务器待处理操作",
        "Server rejected ops": "服务器拒绝操作",
        "Server rejected sync work": "服务器拒绝了同步工作",
        "Server URL": "服务器 URL",
        "Selected icon": "当前图标",
        "Schema": "Schema",
        "Schedule": "计划",
        "Settings": "设置",
        "Setup": "设置中",
        "Share": "分享",
        "Short note": "简短说明",
        "Show Tags in Timeline": "在时间线显示标签",
        "Show Memories in Timeline": "在时间线显示回忆",
        "Show This Month": "显示本月",
        "SF Symbol name": "SF Symbol 名称",
        "Sign in required": "需要登录",
        "Sign in to iCloud in iOS Settings to use iCloud Sync.": "请先在 iOS 设置中登录 iCloud，才能使用 iCloud 同步。",
        "Snapshot": "快照",
        "Source of truth": "权威数据源",
        "Started": "开始时间",
        "Status": "状态",
        "Storage": "存储",
        "Storage & Diagnostics": "存储与诊断",
        "State Response": "状态回应",
        "Summary": "摘要",
        "Summary failed": "摘要失败",
        "Summary ready": "摘要已完成",
        "Summary regenerating": "摘要正在重新生成",
        "Summary update failed": "摘要更新失败",
        "Support": "支持",
        "Succeeded": "成功",
        "Sync": "同步",
        "Sync Doctor": "同步医生",
        "Sync Health": "同步健康",
        "Sync Now": "立即同步",
        "Synced": "已同步",
        "Syncing": "同步中",
        "Testing": "测试",
        "These tools write explicit test records to your private iCloud database and should only be used for troubleshooting.": "这些工具会向你的私有 iCloud 数据库写入明确的测试记录，只应在排查问题时使用。",
        "System-managed": "系统管理",
        "System": "跟随系统",
        "Temporarily unavailable": "暂时不可用",
        "Tag": "标签",
        "Tag already exists": "标签已存在",
        "Tag color": "标签颜色",
        "Tags": "标签",
        "Apply Cleanup?": "应用整理建议？",
        "Cleanup Suggestions": "整理建议",
        "Merge similar topics": "合并相似主题",
        "Move topic to area": "移动到分类方向",
        "Search Topics": "搜索主题",
        "and keep it as an alias of": "并保留为别名，指向",
        "to": "到",
        "This iPhone": "这台 iPhone",
        "This iPhone has local changes or media uploads waiting to sync.": "这台 iPhone 有本地变更或媒体上传等待同步。",
        "This iPhone is behind": "这台 iPhone 落后于 Mac",
        "This iPhone SQLite": "这台 iPhone 的 SQLite",
        "Timeline": "时间线",
        "Themes": "主题",
        "Too dry": "太干",
        "Too much inference": "推断太多",
        "Topic": "主题",
        "Topic Tags": "主题标签",
        "Topics": "主题",
        "Total": "总计",
        "Transcribing": "转录中",
        "Type": "类型",
        "Use Camera": "使用相机",
        "Usage": "使用次数",
        "Default zone test uploaded": "默认 zone 测试已上传",
        "Display preferences only change what is shown. Tags, memories, and generated summaries remain stored locally.": "显示偏好只改变界面展示。标签、回忆和生成摘要仍会保存在本机。",
        "Smoke test uploaded": "Smoke test 已上传",
        "Sync finished: %d uploaded, %d downloaded, %d deleted.": "同步完成：上传 %d 条，下载 %d 条，删除 %d 条。",
        "Sync finished: %d uploaded, %d downloaded, %d deleted, %d failed, %d deferred.": "同步完成：上传 %d 条，下载 %d 条，删除 %d 条，失败 %d 条，延后 %d 条。",
        "Waiting": "等待",
        "Work & Home": "工作与家庭",
        "Choose one media type at a time.": "一次请选择一种媒体类型。",
        "You can add up to 9 audio clips.": "最多可以添加 9 段音频。",
        "You can add up to 9 photos.": "最多可以添加 9 张照片。",
        "Ownlight will use your Apple iCloud account and CloudKit private database. Your current local library will be queued for private iCloud sync in small background batches. Your local data stays on this iPhone.": "Ownlight 会使用你的 Apple iCloud 账号和 CloudKit 私有数据库。你当前的本机内容库会以小批量后台任务排队同步到私人 iCloud；你的本机数据仍然保留在这台 iPhone 上。",
        "Turn on iCloud Sync before running CloudKit actions.": "请先开启 iCloud 同步，再运行 CloudKit 操作。",
        "Turn on iCloud Sync?": "开启 iCloud 同步？",
        "Turn On": "开启",
        "Uploaded one explicit test Moment to your private iCloud database. Moment ID: %@.": "已向你的私有 iCloud 数据库上传一条明确的测试记录。记录 ID：%@。",
        "Uploaded one tiny probe to the default private CloudKit zone. Record name: %@.": "已向默认私有 CloudKit zone 上传一条很小的 probe。记录名：%@。",
        "Writes one tiny CloudKit probe to the default private zone, then tries to delete it. Use this only for diagnosing container setup.": "向默认私有 zone 写入一条很小的 CloudKit probe，然后尝试删除。这个按钮只用于诊断容器配置。",
        "Your local Ownlight data can be included in iPhone iCloud Backup when iCloud Backup and Ownlight backup are enabled in iOS Settings.": "当 iOS 设置中启用 iCloud Backup 且 Ownlight 备份未被关闭时，本地 Ownlight 数据可以包含在 iPhone iCloud Backup 中。",
        "Always summarize in Chinese": "始终用中文总结",
        "Always summarize in English": "始终用英文总结",
        "Accepted": "已允许",
        "AI Summaries": "AI 摘要",
        "AI summaries still running": "AI 摘要仍在处理",
        "AI summaries are still processing on the Mac. This does not block sync.": "AI 摘要仍在 Mac 上处理。这不会阻塞同步。",
        "AI Privacy Permission": "AI 隐私许可",
        "AI Token Usage": "AI Token 用量",
        "AI tags": "AI 标签",
        "AI decides": "由 AI 决定",
        "AI & Analysis": "AI 与分析",
        "AI runs on this iPhone using the providers you configure. Credentials stay in this device Keychain.": "AI 在这台 iPhone 上使用你配置的 provider 运行。凭证只保存在本机 Keychain。",
        "AI runs on this iPhone using the providers you configure. Credentials stay in this device Keychain. Audio failures can come from transcription before the text provider is called.": "AI 在这台 iPhone 上使用你配置的 provider 运行。凭证只保存在本机 Keychain。音频失败可能发生在转录阶段，此时还没有调用文本 provider。",
        "Add an API provider to generate summaries, titles, tags, and reviews.": "添加一个 API provider 后即可生成摘要、标题、标签和回顾。",
        "Add Provider": "添加 Provider",
        "Allow AI Processing": "允许 AI 处理",
        "Add comment": "添加评论",
        "All Moments": "全部记录",
        "All time": "总累计",
        "All synced": "全部已同步",
        "Advanced only": "仅高级选项",
        "Advanced Transcription": "高级转录",
        "Any Match": "任意命中",
        "Apply": "应用",
        "Apply Color": "应用颜色",
        "Archive Selected": "归档所选",
        "Audio": "音频",
        "Audio input": "音频输入",
        "Audio is transcribed first, then summarized by the text analysis provider. Local Gateway is an advanced private transport to a Mac-local model.": "音频会先转录，再交给文本分析 provider 总结。Local Gateway 是高级选项，用来私密连接 Mac 本地模型。",
        "Audio is transcribed first, then summarized by the text analysis provider. External providers use OpenAI-compatible transcription format; Local Gateway is a preset for a Mac-local model.": "音频会先转录，再交给文本分析 provider 总结。外部 provider 使用 OpenAI-compatible 转录格式；Local Gateway 是 Mac 本地模型的一个预设。",
        "Audio is transcribed first, then summarized by the text analysis provider. External providers use OpenAI-compatible transcription format. Local Gateway, LAN, Tailscale, or Cloudflare are connection choices, not separate provider types.": "音频会先转录，再交给文本分析 provider 总结。外部 provider 使用 OpenAI-compatible 转录格式。Local Gateway、LAN、Tailscale 或 Cloudflare 只是连接方式，不再是单独的 provider 类型。",
        "Audio moment": "音频记录",
        "Avg/active day": "活跃日均",
        "API Key": "API Key",
        "Base URL": "Base URL",
        "Bearer Token": "Bearer Token",
        "Before AI runs, Ownlight needs your permission to send private content to the provider or endpoint you configure.": "AI 运行前，Ownlight 需要先得到你的许可，才会把私密内容发送给你配置的 provider 或 endpoint。",
        "Busiest day": "最多的一天",
        "Cancel comment": "取消评论",
        "Cached input": "缓存输入",
        "Check-ins": "打卡",
        "Check-ins rhythm": "打卡节奏",
        "Checking": "检查中",
        "Checking storage": "正在检查存储",
        "Change Color Selected...": "修改所选颜色...",
        "Clear downloaded media cache?": "清除已下载媒体缓存？",
        "Clear filters": "清除筛选",
        "Close video": "关闭视频",
        "Collapse all details": "收起全部详情",
        "Color": "颜色",
        "Comment": "评论",
        "Commenting on:": "评论：",
        "Comments can be up to": "评论最多",
        "Continue editing draft?": "继续编辑草稿？",
        "Custom OpenAI-compatible": "自定义 OpenAI-compatible",
        "Custom provider Test Connection calls /v1/models. It does not upload audio.": "自定义 provider 的 Test Connection 会调用 /v1/models，不会上传音频。",
        "Delete Selected": "删除所选",
        "Delete Tag Permanently?": "永久删除标签？",
        "Delete Tags Permanently?": "永久删除标签？",
        "Delete moment": "删除记录",
        "Details": "详情",
        "Discard edit draft?": "丢弃编辑草稿？",
        "Downloaded full audio and video files will be removed from this iPhone. They can be downloaded again from your Mac when played.": "已下载的完整音频和视频会从这台 iPhone 移除。之后播放时可以再从 Mac 下载。",
        "Duration": "时长",
        "Data Storage": "数据存储",
        "Default": "默认",
        "Edit moment": "编辑记录",
        "Edit tags": "编辑标签",
        "Edited": "已编辑",
        "Enable AI Analysis": "启用 AI 分析",
        "Enabled": "已启用",
        "Estimated requests": "估算请求",
        "External AI Permission": "外部 AI 许可",
        "External transcription remains an advanced option. The first version keeps iPhone transcription as the default.": "外部转录仍是高级选项。首版默认使用 iPhone 本机转录。",
        "Failed requests": "失败请求",
        "Editing is available after this moment finishes syncing.": "这条记录完成同步后可以编辑。",
        "Failed uploads": "上传失败",
        "Expand all details": "展开全部详情",
        "Endpoint": "端点",
        "Format": "格式",
        "Gateway URL": "Gateway URL",
        "Gateway responded with model": "Gateway 返回模型",
        "Highlights": "重点",
        "Key Points": "要点",
        "Language": "语言",
        "Last import": "上次导入",
        "Linked to": "已连接到",
        "Local SQLite is the source of truth.": "本机 SQLite 是权威数据源。",
        "Local-first": "本地优先",
        "Local Gateway": "Local Gateway",
        "Local Gateway Test Connection only calls /health. It does not upload audio.": "Local Gateway 的 Test Connection 只调用 /health，不会上传音频。",
        "Local Gateway settings were saved on this iPhone.": "Local Gateway 设置已保存在这台 iPhone。",
        "Mac / Server Sync": "Mac / Server 同步",
        "Model": "模型",
        "Needs setup": "需要配置",
        "No text analysis provider configured.": "尚未配置文本分析 provider。",
        "Not supported": "不支持",
        "Off until you configure a provider": "关闭，直到你配置 provider",
        "OpenAI-compatible transcription": "OpenAI-compatible 转录",
        "OpenAI-compatible Endpoint": "OpenAI-compatible Endpoint",
        "On-device": "本机",
        "Opt-in data replication belongs here, not in AI setup.": "可选的数据复制属于这里，不属于 AI 设置。",
        "provider": "provider",
        "providers": "providers",
        "Provider": "Provider",
        "Provider responded with model": "Provider 返回模型",
        "Saved": "已保存",
        "Saved to this iPhone Keychain.": "已保存到这台 iPhone 的 Keychain。",
        "Supported": "支持",
        "Text analysis": "文本分析",
        "Text Analysis Provider": "文本分析 Provider",
        "Test Connection": "测试连接",
        "Test Connection calls /v1/models. It does not upload audio.": "Test Connection 会调用 /v1/models，不会上传音频。",
        "This archive can be used for migration and restore checks. Import currently restores into an empty local library only.": "这个归档包可用于迁移和恢复检查。目前导入仅能恢复到空的本机资料库。",
        "This archive can include private text, comments, AI summaries, reviews, check-ins, and media. It is not encrypted.": "这个归档可能包含私密正文、评论、AI 摘要、回顾、打卡和媒体，且不会加密。",
        "Preparing archive": "正在准备归档",
        "Test Connection only calls /health. It does not upload audio.": "Test Connection 只调用 /health，不会上传音频。",
        "Testing Connection": "正在测试连接",
        "Only to the AI or transcription provider you configure. Provider privacy and retention follow that provider.": "只会发送给你配置的 AI 或转录 provider。对方的隐私和保留规则由该 provider 决定。",
        "iCloud Sync & Backup": "iCloud 同步与备份",
        "Keep a separate backup before relying on an export package for device migration.": "在依赖导出包做设备迁移前，请保留独立备份。",
        "iPhone On-device": "iPhone 本机",
        "iPhone on-device transcription": "iPhone 本机转录",
        "iPhone on-device transcription does not need a connection test.": "iPhone 本机转录不需要测试连接。",
        "The bearer token stays in this iPhone Keychain. URL and model stay in local settings only.": "Bearer token 只保存在这台 iPhone 的 Keychain。URL 和模型只保存在本机设置。",
        "The API key stays in this iPhone Keychain. Base URL and model stay in local settings only.": "API key 只保存在这台 iPhone 的 Keychain。Base URL 和模型只保存在本机设置。",
        "API keys stay in this iPhone Keychain. Core recording works without AI. You can reset this permission later in Settings.": "API key 只保存在这台 iPhone 的 Keychain。核心记录功能不需要 AI。之后也可以在 Settings 里重置这个许可。",
        "Moment text, local transcripts, review context, topic names, and audio when you use an external transcription endpoint.": "记录正文、本机转写、回顾上下文、主题名称，以及使用外部转录接口时的音频。",
        "Ownlight asks before sending private content to the provider you configure.": "Ownlight 会在把私密内容发送给你配置的 provider 前先征得许可。",
        "Transcription Provider": "转录 Provider",
        "Transcription provider settings were saved on this iPhone.": "转录 provider 设置已保存在这台 iPhone。",
        "Use same provider for transcription": "转录使用同一个 provider",
        "What may be sent": "可能发送什么",
        "What stays here": "什么留在本机",
        "Where it goes": "发送到哪里",
        "Available when the selected provider supports transcription. Otherwise audio stays text-first: transcribe locally, then summarize with the text provider.": "当所选 provider 支持转录时可用。否则音频仍走 text-first：先本机转录，再交给文本 provider 总结。",
        "Drag providers to set fallback priority. Automatic fallback only uses providers after transient failures.": "拖拽 provider 设置 fallback 优先级。自动 fallback 只会在临时失败后使用下一个 provider。",
        "Generated Artifacts": "生成内容",
        "Generated artifact settings take effect when AI Analysis is enabled.": "生成内容设置会在 AI 分析开启后生效。",
        "Weekly Review uses AI to summarize recent moments into a private recap. Publish Weekly Review inserts each automatically generated review into your Timeline as a Moment.": "每周回顾会用 AI 整理最近的记录，生成一篇只给自己看的回顾。开启后，每次自动生成的回顾都会加入时间线，成为一条记录。",
        "Loading": "加载中",
        "Log in to sync": "登录以同步",
        "Logs": "日志",
        "Long press to delete comment": "长按删除评论",
        "Less": "更少",
        "Sync endpoint unavailable": "同步端点不可用",
        "Matched comment": "命中评论",
        "Matched summary": "命中摘要",
        "Matched tag": "命中标签",
        "Matched text": "命中正文",
        "Matched transcript": "命中文稿",
        "Media summaries": "媒体摘要",
        "Mac media uploads need inspection": "Mac 媒体上传需要检查",
        "Mac Storage": "Mac 存储",
        "Merge Selected Into": "合并所选到",
        "Moment unavailable": "记录不可用",
        "More": "更多",
        "Move image left": "向左移动图片",
        "Move image right": "向右移动图片",
        "New moment": "新记录",
        "New topic": "新主题",
        "No matching moments": "没有匹配的记录",
        "No moments": "没有记录",
        "No results": "没有结果",
        "Open image": "打开图片",
        "Open video": "打开视频",
        "Photo access denied": "没有照片访问权限",
        "Photo moment": "照片记录",
        "Pin moment": "置顶记录",
        "Pinned": "置顶",
        "Post Text": "正文",
        "Regenerating summary...": "正在重新生成摘要...",
        "Recommended": "建议",
        "Remote changes": "远端变更",
        "Remove": "移除",
        "Remove audio": "移除音频",
        "Remove image": "移除图片",
        "Remove video": "移除视频",
        "Requests": "请求数",
        "Restore it from the Archived section instead of creating a duplicate.": "请从已归档区域恢复它，而不是创建重复标签。",
        "Save failed": "保存失败",
        "Save image to Photos": "保存图片到照片",
        "Saved to Photos": "已保存到照片",
        "Selected topic tags will be archived and kept as aliases of the target.": "所选主题标签会被归档，并作为目标标签的别名保留。",
        "Selected Primary Tags": "已选主标签",
        "Share image": "分享图片",
        "Show less": "收起",
        "See Sync Health for raw metrics": "查看 Sync Health 原始指标",
        "Signals": "信号",
        "Stuck for": "卡住",
        "Start with one Sync Now retry. If it still fails, verify the configured Server URL and that the private endpoint is reachable.": "先点击一次立即同步重试。如果仍然失败，请确认已配置的 Server URL，并检查私有端点是否可连接。",
        "Summarizing": "总结中",
        "Summarizing...": "正在总结...",
        "Summary unavailable": "摘要不可用",
        "Sync Doctor only uses existing Sync Health signals. Repair actions run only when tapped.": "Sync Doctor 只使用现有 Sync Health 信号。修复动作只会在你点击后执行。",
        "Tag names are shared across": "标签名称在以下类型中共享：",
        "Tap Sync Now to retry. If it still fails, check the configured private endpoint or remote access URL.": "点击立即同步重试。如果仍然失败，请检查已配置的私有端点或远程访问 URL。",
        "Tap or drag to inspect": "轻点或拖动查看",
        "Text": "文本",
        "Time": "时间",
        "Time Heatmap": "时间热力图",
        "Time Insights": "时间洞察",
        "Time Line": "时间折线",
        "Time visualization": "时间可视化",
        "The current summary will update when the new result is ready.": "新结果完成后，当前摘要会自动更新。",
        "The Mac reports failed media uploads. Check Sync Health and Mac logs before retrying.": "Mac 报告有失败的媒体上传。重试前请查看 Sync Health 和 Mac 日志。",
        "The previous summary is still available. Try regenerating again when the Mac is reachable.": "之前的摘要仍可查看。Mac 可连接时可以再试一次。",
        "The previous summary is still available. Check the provider or transcript, then regenerate.": "之前的摘要仍可查看。检查 provider 或转录原文后再重新生成。",
        "There is an unsaved edit draft for this moment.": "这条记录有一份未保存的编辑草稿。",
        "This can take a moment.": "这可能需要一点时间。",
        "This iPhone cursor": "这台 iPhone 游标",
        "This month": "本月",
        "This week": "本周",
        "Diagnostics here are local to this iPhone. Mac/server replication diagnostics only appear when that layer is configured.": "这里的诊断只针对这台 iPhone。Mac/server 复制层诊断只会在配置该层后出现。",
        "Transcript is not available yet.": "转录文稿暂不可用。",
        "Today": "今天",
        "Choose Time Line or Time Heatmap in Manage to show insights here.": "在 Manage 中选择时间折线或时间热力图后，这里会显示洞察。",
        "Daily reset": "每日重置",
        "This removes": "这会移除",
        "This removes only the generated AI summary.": "这只会移除生成的 AI 摘要。",
        "This removes the moment from your timeline and syncs the deletion to your Mac.": "这会从时间线删除这条记录，并同步到你的其他设备。",
        "This updates only the color of selected primary tags.": "这里只会更新所选主标签的颜色。",
        "Topics appear after AI summaries create them.": "主题标签会在 AI 摘要生成后出现。",
        "Transcribing media...": "正在转录媒体...",
        "Transcription failed": "转录失败",
        "Transcription failed.": "转录失败。",
        "Transcription is still running.": "仍在转录中。",
        "Transcript": "文稿",
        "Saved privately on this iPhone for search and diagnostics.": "仅私密保存在这台 iPhone 上，用于搜索和排查。",
        "Only one document can be added.": "一次只能添加一个文档。",
        "Only PDF files are supported right now.": "目前只支持 PDF 文件。",
        "Open document": "打开文档",
        "Original Text": "原文",
        "PDF document": "PDF 文档",
        "View original text": "查看原文",
        "Tokens": "Token",
        "Input": "输入",
        "Output": "输出",
        "Tokens unavailable": "Token 用量不可用",
        "Tap to preview": "点击预览",
        "Turn on AI & Analysis to generate weekly reviews.": "开启 AI 与分析后才能生成每周回顾。",
        "Try again after sync finishes.": "同步完成后再试一次。",
        "Try regenerating again when the Mac is reachable.": "Mac 可连接时可以再重新生成。",
        "Check the provider or transcript, then regenerate.": "检查 provider 或转录原文后再重新生成。",
        "Unavailable": "不可用",
        "Uncertainty": "不确定性",
        "Unsupported file type.": "不支持的文件类型。",
        "Unpin moment": "取消置顶记录",
        "Updated": "更新于",
        "Uptime": "运行时间",
        "Useful": "有用",
        "Use this only when this iPhone looks out of date. Normal sync is enough for daily use.": "只有当这台 iPhone 看起来明显落后时才使用。日常使用普通同步就够了。",
        "Video": "视频",
        "Video moment": "视频记录",
        "Video unavailable": "视频不可用",
        "Version": "版本",
        "Voice note": "语音记录",
        "Check Sync Health and Mac logs before retrying rejected sync work.": "重试被拒绝的同步工作前，请先查看 Sync Health 和 Mac 日志。",
        "Failed media uploads are waiting on this iPhone.": "这台 iPhone 上有失败的媒体上传等待处理。",
        "Media needs re-download": "媒体需要重新下载",
        "Some uploaded media is missing locally and can be downloaded again.": "部分已上传媒体在本机缺失，可以重新下载。",
        "Sync work is waiting": "同步工作正在等待",
        "Uploads need retry": "上传需要重试",
        "Your Mac has newer changes than this iPhone.": "Mac 上有比这台 iPhone 更新的变更。",
        "Weekday x time": "星期 x 时间",
        "Weekly Review": "每周回顾",
        "Keywords": "关键词",
        "Range": "时间范围",
        "Source": "来源",
        "Yes": "是",
        "What did it miss?": "它漏掉了什么？",
        "Worth Revisiting": "值得回看",
        "View all": "查看全部",
        "View in Timeline": "在时间线查看",
        "View review": "查看回顾",
        "With Photos": "含照片",
        "Yesterday": "昨天",
        "already exists as a": "已经是",
        "and": "和",
        "1 moment": "1 条记录",
        "archived tags from Tags, aliases, and moments. Their names will be available again.": "个已归档标签，以及相关别名和记录关联。这些名称之后可以重新使用。",
        "behind": "条落后",
        "characters.": "个字符。",
        "chars": "字符",
        "comments": "条评论",
        "failed uploads": "个上传失败",
        "filter": "筛选",
        "Last export": "上次导出",
        "Export Details": "导出详情",
        "Export does not include API keys, provider credentials, or private transcript text.": "导出不包含 API Key、provider 凭证或私密转录文本。",
        "Export includes structured JSON, Markdown preview, and media files currently available on this iPhone.": "导出包含结构化 JSON、Markdown 预览，以及当前这台 iPhone 上可用的媒体文件。",
        "Exports can contain private data and are not encrypted.": "导出可能包含隐私数据，且不会加密。",
        "Archive contents": "归档内容",
        "Local database is not ready.": "本机数据库尚未就绪。",
        "requests": "次请求",
        "from Tags, aliases, and moments. The name will be available again for a new Primary or Topic Tag.": "从标签、别名和记录中移除。这个名称之后可以重新用于新的主标签或主题标签。",
        "audio": "段音频",
        "image": "张图片",
        "is already in": "已经存在于",
        "is archived under": "已归档于",
        "Media moment": "媒体记录",
        "media files": "个媒体文件",
        "missing": "缺失",
        "moments": "条记录",
        "Next month": "下个月",
        "No activity": "暂无活动",
        "of": "/",
        "Open day in Timeline. Long press for preview.": "打开这一天的时间线。长按可预览。",
        "pending changes": "个待同步变更",
        "pending uploads": "个待上传",
        "photo": "张照片",
        "Photos": "照片",
        "photos": "张照片",
        "text": "条文本",
        "texts": "条文本",
        "this moment": "这条记录",
        "topics": "个主题",
        "uses": "次使用",
        "video": "个视频",
        "videos": "个视频",
    ]
}

enum DefaultPrimaryTagLocalization {
    private static let englishByChineseName: [String: String] = [
        "日记": "Diary",
        "想法": "Thoughts",
        "学习整理": "Study",
        "情绪": "Mood",
        "碎碎念": "Random",
        "复盘": "Review",
    ]

    static func displayName(for storedName: String, language: AppResolvedLanguage) -> String {
        guard language == .english else {
            return chineseName(for: storedName) ?? storedName
        }

        return englishName(for: storedName) ?? storedName
    }

    static func searchNames(for storedName: String) -> [String] {
        var names = [storedName]
        if let chinese = chineseName(for: storedName), !names.contains(chinese) {
            names.append(chinese)
        }
        if let english = englishName(for: storedName), !names.contains(english) {
            names.append(english)
        }
        return names
    }

    private static func englishName(for storedName: String) -> String? {
        if let english = englishByChineseName[storedName] {
            return english
        }

        return englishByChineseName.first { $0.value.caseInsensitiveCompare(storedName) == .orderedSame }?.value
    }

    private static func chineseName(for storedName: String) -> String? {
        if englishByChineseName[storedName] != nil {
            return storedName
        }

        return englishByChineseName.first { $0.value.caseInsensitiveCompare(storedName) == .orderedSame }?.key
    }
}
