import Foundation

enum AIProviderSourceFormatter {
    static func label(provider: String?, model: String?, language: AppResolvedLanguage) -> String? {
        let parts = [displayProvider(provider), displayModel(model)].compactMap { $0 }
        guard !parts.isEmpty else {
            return nil
        }

        return "\(L10n.t("Generated by", language)) \(parts.joined(separator: " · "))"
    }

    private static func displayProvider(_ value: String?) -> String? {
        guard let normalized = normalized(value) else {
            return nil
        }

        switch normalized.lowercased() {
        case "openai":
            return "OpenAI"
        case "deepseek":
            return "DeepSeek"
        case "local":
            return "Local"
        default:
            return normalized
        }
    }

    private static func displayModel(_ value: String?) -> String? {
        normalized(value)
    }

    private static func normalized(_ value: String?) -> String? {
        guard let value else {
            return nil
        }

        let trimmed = value.trimmingCharacters(in: .whitespacesAndNewlines)
        return trimmed.isEmpty ? nil : trimmed
    }
}
