UPDATE "tags"
SET "area_id" = CASE
  WHEN lower("name") LIKE '%ai%'
    OR lower("name") LIKE '%llm%'
    OR lower("name") LIKE '%gpt%'
    OR lower("name") LIKE '%claude%'
    OR lower("name") LIKE '%codex%'
    OR lower("name") LIKE '%mcp%'
    OR lower("name") LIKE '%api%'
    OR lower("name") LIKE '%http%'
    OR lower("name") LIKE '%ios%'
    OR lower("name") LIKE '%swift%'
    OR lower("name") LIKE '%python%'
    OR lower("name") LIKE '%typescript%'
    OR lower("name") LIKE '%javascript%'
    OR lower("name") LIKE '%sqlite%'
    OR lower("name") LIKE '%server%'
    OR lower("name") LIKE '%cloudflare%'
    OR lower("name") LIKE '%tailscale%'
    OR lower("name") LIKE '%github%'
    OR lower("name") LIKE '%docker%'
    OR "name" LIKE '%代码%'
    OR "name" LIKE '%编程%'
    OR "name" LIKE '%开发%'
    OR "name" LIKE '%软件%'
    OR "name" LIKE '%服务器%'
    OR "name" LIKE '%数据库%'
    OR "name" LIKE '%接口%'
    OR "name" LIKE '%网络%'
    OR "name" LIKE '%安全%'
    OR "name" LIKE '%证书%'
    OR "name" LIKE '%中间人%'
    OR "name" LIKE '%模型%'
    OR "name" LIKE '%技术%'
  THEN 'technology'
  WHEN lower("name") LIKE '%product%'
    OR lower("name") LIKE '%design%'
    OR lower("name") LIKE '%ui%'
    OR lower("name") LIKE '%ux%'
    OR lower("name") LIKE '%figma%'
    OR lower("name") LIKE '%feature%'
    OR lower("name") LIKE '%roadmap%'
    OR lower("name") LIKE '%filter%'
    OR lower("name") LIKE '%topic%'
    OR lower("name") LIKE '%tag%'
    OR "name" LIKE '%产品%'
    OR "name" LIKE '%设计%'
    OR "name" LIKE '%界面%'
    OR "name" LIKE '%交互%'
    OR "name" LIKE '%功能%'
    OR "name" LIKE '%路线图%'
    OR "name" LIKE '%筛选%'
    OR "name" LIKE '%标签%'
    OR "name" LIKE '%体验%'
  THEN 'product_design'
  WHEN lower("name") LIKE '%learning%'
    OR lower("name") LIKE '%study%'
    OR lower("name") LIKE '%knowledge%'
    OR lower("name") LIKE '%research%'
    OR lower("name") LIKE '%paper%'
    OR lower("name") LIKE '%thesis%'
    OR lower("name") LIKE '%book%'
    OR lower("name") LIKE '%course%'
    OR lower("name") LIKE '%reading%'
    OR "name" LIKE '%学习%'
    OR "name" LIKE '%知识%'
    OR "name" LIKE '%论文%'
    OR "name" LIKE '%研究%'
    OR "name" LIKE '%读书%'
    OR "name" LIKE '%课程%'
    OR "name" LIKE '%笔记%'
    OR "name" LIKE '%整理%'
  THEN 'learning_knowledge'
  WHEN lower("name") LIKE '%work%'
    OR lower("name") LIKE '%office%'
    OR lower("name") LIKE '%business%'
    OR lower("name") LIKE '%meeting%'
    OR lower("name") LIKE '%client%'
    OR lower("name") LIKE '%deadline%'
    OR lower("name") LIKE '%job%'
    OR "name" LIKE '%工作%'
    OR "name" LIKE '%会议%'
    OR "name" LIKE '%客户%'
    OR "name" LIKE '%岗位%'
    OR "name" LIKE '%面试%'
    OR "name" LIKE '%任务%'
    OR "name" LIKE '%同事%'
  THEN 'work'
  WHEN lower("name") LIKE '%health%'
    OR lower("name") LIKE '%fitness%'
    OR lower("name") LIKE '%exercise%'
    OR lower("name") LIKE '%sport%'
    OR lower("name") LIKE '%run%'
    OR lower("name") LIKE '%sleep%'
    OR lower("name") LIKE '%medicine%'
    OR lower("name") LIKE '%rehab%'
    OR lower("name") LIKE '%gym%'
    OR "name" LIKE '%健康%'
    OR "name" LIKE '%运动%'
    OR "name" LIKE '%跑步%'
    OR "name" LIKE '%健身%'
    OR "name" LIKE '%睡眠%'
    OR "name" LIKE '%康复%'
    OR "name" LIKE '%训练%'
    OR "name" LIKE '%饮食%'
    OR "name" LIKE '%药%'
  THEN 'health_fitness'
  WHEN lower("name") LIKE '%emotion%'
    OR lower("name") LIKE '%relationship%'
    OR lower("name") LIKE '%mood%'
    OR lower("name") LIKE '%family%'
    OR lower("name") LIKE '%friend%'
    OR lower("name") LIKE '%love%'
    OR lower("name") LIKE '%stress%'
    OR lower("name") LIKE '%anxiety%'
    OR "name" LIKE '%情绪%'
    OR "name" LIKE '%关系%'
    OR "name" LIKE '%心情%'
    OR "name" LIKE '%家人%'
    OR "name" LIKE '%朋友%'
    OR "name" LIKE '%压力%'
    OR "name" LIKE '%焦虑%'
    OR "name" LIKE '%亲密%'
  THEN 'emotion_relationships'
  ELSE 'life'
END
WHERE "type" = 'topic'
  AND (
    "area_id" IS NULL
    OR "area_id" = ''
    OR "area_id" NOT IN (
      'technology',
      'product_design',
      'learning_knowledge',
      'work',
      'life',
      'health_fitness',
      'emotion_relationships'
    )
  );
